The PHP DOM extension is required
I'm getting the following error when running a test scenario on a minimal Ubuntu Bionic image:

```
Fatal error: Class 'DOMDocument' not found (Behat\Testwork\Call\Exception\FatalThrowableError)
```

It is thrown in `Behat\Testwork\Output\Printer\JUnitOutputPrinter`.