ReturnTypeTransformation: Add support for php 7.4
> Fatal error: 8192: Function ReflectionType::__toString() is deprecated in vendor/behat/behat/src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php line 133

Since getName() is not documented, I am not sure from which PHP version it is available.

Behat 3.5 is for PHP 5.6+, is that correct ?

In case `getName()` is missing in some PHP version it would require a : 

```
return method_exists($type, 'getName') ? $type->getName(); : (string) $type;
```